version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localpost
    volumes:
      - ./db-data:/var/lib/postgresql/data/ # Persist data
    ports:
      - 5432:5432
