CREATE TABLE IF NOT EXISTS earlyaccess (
  ID SERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT
);

CREATE TABLE IF NOT EXISTS user (
  ID SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  password TEXT,
  created_at TIMESTAMP,
)